In [3]:
import pandas as pd 
import numpy as np

In [4]:
netflix = pd.read_csv('netflix_titles.csv')
netflix.head()

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description  
0  In a future where the elite inhabit an island ...  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...

In [5]:
print(netflix.columns)
print(len(netflix.columns))

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')
12


In [6]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB


In [7]:
netflix.isna().sum() # director, cast, country, date_added, rating 

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [8]:
netflix.dropna(inplace = True)
netflix.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [9]:
# 필요한 변수를 찾는다. 
netflix_need = netflix[['type', 'title','country', 'release_year','rating','listed_in', 'description']]
netflix_need.head()

type  title        country  release_year rating  \
1    Movie   7:19         Mexico          2016  TV-MA   
2    Movie  23:59      Singapore          2011      R   
3    Movie      9  United States          2009  PG-13   
4    Movie     21  United States          2008  PG-13   
5  TV Show     46         Turkey          2016  TV-MA   

                                           listed_in  \
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   
5    International TV Shows, TV Dramas, TV Mysteries   

                                         description  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...  
5  A genetics professor experiments with a treatm...

In [10]:
netflix_need['type'].value_counts() # Movie or TV Show

Movie      4673
TV Show     135
Name: type, dtype: int64

In [11]:
netflix_movie = netflix_need[netflix_need['type'] == 'Movie']
print(netflix_movie.shape)

netflix_movie.head() # 4673 by 7

(4673, 7)


type  title        country  release_year rating  \
1  Movie   7:19         Mexico          2016  TV-MA   
2  Movie  23:59      Singapore          2011      R   
3  Movie      9  United States          2009  PG-13   
4  Movie     21  United States          2008  PG-13   
6  Movie    122          Egypt          2019  TV-MA   

                                           listed_in  \
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   
6                Horror Movies, International Movies   

                                         description  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...  
6  After an awful accident, a couple admitted to ...

In [12]:
netflix_TVshow = netflix_need[netflix_need['type'] == 'TV Show']
print(netflix_TVshow.shape)

netflix_TVshow.head() # 135 by 7

(135, 7)


type            title                country  release_year rating  \
5    TV Show               46                 Turkey          2016  TV-MA   
132  TV Show        7 (Seven)                  India          2019  TV-14   
218  TV Show  A Queen Is Born                 Brazil          2020  TV-14   
260  TV Show         A.I.C.O.                  Japan          2018  TV-14   
276  TV Show     Abby Hatcher  United States, Canada          2019   TV-Y   

                                           listed_in  \
5    International TV Shows, TV Dramas, TV Mysteries   
132                                         TV Shows   
218               International TV Shows, Reality TV   
260             Anime Series, International TV Shows   
276                                         Kids' TV   

                                           description  
5    A genetics professor experiments with a treatm...  
132  Multiple women report their husbands as missin...  
218  Gloria Groove and Alexia Twister make drag dre...  
260  Everything Aiko knew was a lie. Now she's join...  
276  A big-hearted girl helps her Fuzzly friends wh...

In [13]:
netflix_movie.head()

type  title        country  release_year rating  \
1  Movie   7:19         Mexico          2016  TV-MA   
2  Movie  23:59      Singapore          2011      R   
3  Movie      9  United States          2009  PG-13   
4  Movie     21  United States          2008  PG-13   
6  Movie    122          Egypt          2019  TV-MA   

                                           listed_in  \
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   
6                Horror Movies, International Movies   

                                         description  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...  
6  After an awful accident, a couple admitted to ...

In [14]:
netflix_movie_new = netflix_movie[netflix_movie['release_year'] > 2005]
netflix_movie_new.reset_index(inplace = True)

In [69]:
del netflix_movie_new['index']

In [57]:
netflix_movie_new.head().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 1 to 6
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   type          5 non-null      object
 1   title         5 non-null      object
 2   country       5 non-null      object
 3   release_year  5 non-null      int64 
 4   rating        5 non-null      object
 5   listed_in     5 non-null      object
 6   description   5 non-null      object
dtypes: int64(1), object(6)
memory usage: 320.0+ bytes


In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(min_df = 2, max_df = 0.7)
tfidf_vec = tfidf.fit_transform(netflix_movie_new['description'])
print(tfidf.get_feature_names()[:7])
print(tfidf_vec.toarray())

['000', '007', '10', '10th', '11', '12', '13']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [138]:
kim = [word for word in tfidf.get_feature_names() if word.isalpha() == True]
kim[:5]

['aaron', 'abandoned', 'abandons', 'abbey', 'abduct']

In [16]:
NEW_MOVIE = pd.DataFrame(tfidf_vec.toarray(), columns = tfidf.get_feature_names(), index = netflix_movie_new['title'])
NEW_MOVIE.head()

000  007   10  10th   11   12   13   14  14th   15  ...  youthful  \
title                                                      ...             
7:19   0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  0.0  ...       0.0   
23:59  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  0.0  ...       0.0   
9      0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  0.0  ...       0.0   
21     0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  0.0  ...       0.0   
122    0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0   0.0  0.0  ...       0.0   

       youtube  zach  zack  zany  zealand  zero  zombie  zombies  zone  
title                                                                   
7:19       0.0   0.0   0.0   0.0      0.0   0.0     0.0      0.0   0.0  
23:59      0.0   0.0   0.0   0.0      0.0   0.0     0.0      0.0   0.0  
9          0.0   0.0   0.0   0.0      0.0   0.0     0.0      0.0   0.0  
21         0.0   0.0   0.0   0.0      0.0   0.0     0.0      0.0   0.0  
122        0.0   0.0   0.0   0.0      0.0   0.0     0.0      0.0   0.0  

[5 rows x 6366 columns]

True

In [77]:
from sklearn.metrics.pairwise import cosine_similarity
net_movie = pd.DataFrame(cosine_similarity(tfidf_vec), columns = netflix_movie_new['title'], index = netflix_movie_new['title'])
net_movie.head()

title      7:19     23:59         9        21       122       706      1920  \
title                                                                         
7:19   1.000000  0.006547  0.020837  0.014333  0.030203  0.004555  0.013421   
23:59  0.006547  1.000000  0.003690  0.000000  0.048548  0.015742  0.067459   
9      0.020837  0.003690  1.000000  0.064654  0.041991  0.003824  0.011513   
21     0.014333  0.000000  0.064654  1.000000  0.000000  0.018511  0.044257   
122    0.030203  0.048548  0.041991  0.000000  1.000000  0.000000  0.031262   

title      1922     2,215      3022  ...   Zinzana      Zion  \
title                                ...                       
7:19   0.011756  0.000000  0.000000  ...  0.011708  0.000000   
23:59  0.024643  0.008106  0.036908  ...  0.003587  0.016052   
9      0.007963  0.014850  0.019940  ...  0.007930  0.011623   
21     0.019686  0.000000  0.007707  ...  0.019605  0.000000   
122    0.049311  0.000000  0.000000  ...  0.008155  0.034916   

title  Zipi & Zape y la Isla del Capitan  Zoé: Panoramas    Zodiac  Zokkomon  \
title                                                                          
7:19                            0.007746        0.004796  0.004886  0.035784   
23:59                           0.082220        0.000000  0.000000  0.036086   
9                               0.004366        0.004026  0.012228  0.007641   
21                              0.010599        0.019491  0.015908  0.003757   
122                             0.020289        0.004909  0.005001  0.007858   

title  Zombieland       Zoo      Zoom    Zubaan  
title                                            
7:19     0.013333  0.012390  0.032156  0.032517  
23:59    0.014925  0.064613  0.018079  0.020955  
9        0.049406  0.017721  0.017636  0.084129  
21       0.047580  0.003613  0.033443  0.020779  
122      0.027233  0.048040  0.035790  0.005233  

[5 rows x 4051 columns]

In [121]:
netflix_movie_new[netflix_movie_new['title']== 'About Time']

type       title         country  release_year rating  \
184  Movie  About Time  United Kingdom          2013      R   

                                  listed_in  \
184  Comedies, Dramas, International Movies   

                                           description  
184  When Tim learns that the men in his family can...

title
7:19          0.012472
23:59         0.060651
9             0.038485
21            0.025038
122           0.019208
                ...   
Zokkomon      0.105187
Zombieland    0.036306
Zoo           0.102617
Zoom          0.023346
Zubaan        0.096712
Name: About Time, Length: 4051, dtype: float64

In [125]:
def movie_recsys(movie, number):
    MOVIE_RECSYS = net_movie[movie].sort_values(ascending = False)
    return MOVIE_RECSYS[1:].head(number)
movie_recsys(movie = 'About Time', number = 10)

title
The Legend of Michael Mishra           0.236086
I Fine... Thank You... Love You        0.229049
World Famous Lover                     0.227109
Like Arrows                            0.219895
Jag älskar dig: En skilsmässokomedi    0.216581
Silver Linings Playbook                0.216197
The Wrong Missy                        0.208311
Captain Underpants Mega Blissmas       0.204803
Revolutionary Road                     0.204801
Baaghi                                 0.197188
Name: About Time, dtype: float64

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfvec = TfidfVectorizer(min_df = 2, max_df = 0.7)
tvshow_vector = tfidfvec.fit_transform(netflix_TVshow['description'])

In [28]:
# feature tokenizer 
tfidfvec.get_feature_names()[:5]

['10', '1950s', 'about', 'accident', 'acclaimed']

In [37]:
print(tvshow_vector.toarray().shape)
print(tvshow_vector.toarray())


(135, 366)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [38]:
# 각 영화별 단어가 얼마만큼 들어가있는지 맵핑해준다.
tvshow_vector = pd.DataFrame(tvshow_vector.toarray(), columns = tfidfvec.get_feature_names(), index = netflix_TVshow['title'])
tvshow_vector.head()

10  1950s  about  accident  acclaimed  action  adaptation  \
title                                                                         
46               0.0    0.0    0.0       0.0        0.0     0.0         0.0   
7 (Seven)        0.0    0.0    0.0       0.0        0.0     0.0         0.0   
A Queen Is Born  0.0    0.0    0.0       0.0        0.0     0.0         0.0   
A.I.C.O.         0.0    0.0    0.0       0.0        0.0     0.0         0.0   
Abby Hatcher     0.0    0.0    0.0       0.0        0.0     0.0         0.0   

                 adventures  after  aftermath  ...      with  woman     women  \
title                                          ...                              
46                      0.0    0.0        0.0  ...  0.240892    0.0  0.000000   
7 (Seven)               0.0    0.0        0.0  ...  0.000000    0.0  0.305882   
A Queen Is Born         0.0    0.0        0.0  ...  0.000000    0.0  0.000000   
A.I.C.O.                0.0    0.0        0.0  ...  0.000000    0.0  0.000000   
Abby Hatcher            0.0    0.0        0.0  ...  0.186083    0.0  0.000000   

                 work  works  world  writer  year  years  young  
title                                                            
46                0.0    0.0    0.0     0.0   0.0    0.0    0.0  
7 (Seven)         0.0    0.0    0.0     0.0   0.0    0.0    0.0  
A Queen Is Born   0.0    0.0    0.0     0.0   0.0    0.0    0.0  
A.I.C.O.          0.0    0.0    0.0     0.0   0.0    0.0    0.0  
Abby Hatcher      0.0    0.0    0.0     0.0   0.0    0.0    0.0  

[5 rows x 366 columns]

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
TVshow = cosine_similarity(tvshow_vector)
TVshow_df = pd.DataFrame(TVshow, index = netflix_TVshow['title'], columns = netflix_TVshow['title'])
TVshow_df.head()

title                  46  7 (Seven)  A Queen Is Born  A.I.C.O.  Abby Hatcher  \
title                                                                           
46               1.000000   0.144101         0.015551  0.088343      0.062678   
7 (Seven)        0.144101   1.000000         0.117900  0.129848      0.076429   
A Queen Is Born  0.015551   0.117900         1.000000  0.076082      0.028304   
A.I.C.O.         0.088343   0.129848         0.076082  1.000000      0.146848   
Abby Hatcher     0.062678   0.076429         0.028304  0.146848      1.000000   

title            Abnormal Summit  Afronta! Facing It!  Age of Rebellion  \
title                                                                     
46                      0.127029             0.055245          0.017116   
7 (Seven)               0.000000             0.118257          0.073279   
A Queen Is Born         0.026929             0.082717          0.011517   
A.I.C.O.                0.036366             0.036885          0.024038   
Abby Hatcher            0.030914             0.115241          0.058188   

title            Almost Happy  Anitta: Made In Honório  ...  \
title                                                   ...   
46                   0.078430                 0.015108  ...   
7 (Seven)            0.032572                 0.016223  ...   
A Queen Is Born      0.192901                 0.083548  ...   
A.I.C.O.             0.054624                 0.125427  ...   
Abby Hatcher         0.045738                 0.159607  ...   

title            Til Death Do Us Part  To the Lake  Toast of London  \
title                                                                 
46                           0.018644     0.016282         0.120668   
7 (Seven)                    0.010010     0.129092         0.000000   
A Queen Is Born              0.064687     0.060478         0.133224   
A.I.C.O.                     0.047420     0.073109         0.021637   
Abby Hatcher                 0.014402     0.072409         0.056462   

title            Trailer Park Boys: The Animated Series  \
title                                                     
46                                             0.000000   
7 (Seven)                                      0.016406   
A Queen Is Born                                0.035078   
A.I.C.O.                                       0.118099   
Abby Hatcher                                   0.000000   

title            Unabomber - In His Own Words   Valeria    Velvet  \
title                                                               
46                                   0.107343  0.016571  0.119307   
7 (Seven)                            0.017791  0.068838  0.071399   
A Queen Is Born                      0.054291  0.045297  0.083117   
A.I.C.O.                             0.069996  0.029940  0.193260   
Abby Hatcher                         0.000000  0.176946  0.127628   

title            Watership Down  World of Winx       You  
title                                                     
46                     0.000000       0.000000  0.051401  
7 (Seven)              0.088882       0.078526  0.000000  
A Queen Is Born        0.166950       0.494391  0.040164  
A.I.C.O.               0.084107       0.061953  0.124772  
Abby Hatcher           0.067789       0.069249  0.143992  

[5 rows x 135 columns]

In [80]:
TVshow_recsys = TVshow_df.loc['46'].sort_values(ascending = False)
TVshow_recsys = TVshow_recsys[1:]
TVshow_recsys.head()


title
Innocent              0.280513
Frozen Planet         0.212828
Hoff the Record       0.199917
Cheese in the Trap    0.194839
Geronimo Stilton      0.175867
Name: 46, dtype: float64